# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# Reach out on Slack at '#github-appsec-security' to get help.

name: "Dependency Review"
on: [pull_request]
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: [self-hosted, linux, x64, ubuntu-22.04]
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: low
          fail-on-scopes: runtime, development
